//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp2_TomasBasso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int IDcliente { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> Dni { get; set; }
        public string Direccion { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
    }
}
