//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp2_TomasBasso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESION
    {
        public int Sesion_ID { get; set; }
        public decimal Usuario_ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora_incio { get; set; }
        public System.DateTime Hora_Finalizacion { get; set; }
    }
}
